name: "刘叽里咕噜婷的小窝"
name_en: "Lau's World"
author: "刘叽里咕噜婷"
author_en: "Lau"
description: "Illustration artist."
url: "https://lettielau.github.io/ljt"
email: "ljt@picsew.cn"
github_url: "https://github.com/LettieLau/ljt/"
excerpt_limit: 100
timezone: Asia/Shanghai

highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

permalink: /posts/contents/:title/
excerpt_limit: 50

sass:
  sass_dir: "/assets/sass/"
  style: compressed

# Plugins
plugins: [jekyll-paginate,liquid] #jekyll-toc,jekyll-asciidoc]
paginate: 6
paginate_path: "/posts/page/:num"

collections:
  posts:
    output: true
  gallery:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: "post"
      active_title: "Posts"
  - scope:
      path: ""
      type: gallery
    values:
      layout: "album"
